service: bot-get-match

provider:
  name: aws
  runtime: ruby2.7
  memorySize: 128
  region: eu-west-3
  stage: dev

functions:
  getMatch:
    handler: handler.getMatch
    description: "Da el resultado de un partido de fútbol"
    events:
      - http:
          path: /
          method: post
    environment:
      TG_TOKEN: ${ssm:bot-get-match-token~true}