service: bot-get-match

provider:
  name: aws
  runtime: ruby2.7
  stage: dev
  region: eu-west-3

functions:
  post:
    handler: handler.getMatch
    events:
      - http:
          path: getMatch
          method: post
          cors: true